project:
  type: website
  output-dir: ../docs

website:
  title: "Landelijk water"
#  navbar:
#    left:
#      - text: Wolvenpolder
#        href: wolvenpolder/opdracht.qmd
#      - text: Eendragt
#        href: eendragt/opdracht.qmd
  
  sidebar:
    logo: img/logo_VHL.jpg
    logo-href: https://www.hydroconsult.nl
    style: "docked"
    search: true
    contents:
      - section: "Studiewijzer"
        contents:
          - section: "Introductie"
            contents:
              - href: studiewijzer/introductie.qmd
                text: Relevantie
              - href: studiewijzer/leerdoelen.qmd
                text: Leerdoelen
              - href: studiewijzer/toetsing.qmd
                text: Toetsing

          - section: "Opdracht"
            contents:
              - href: studiewijzer/opdracht.qmd
                text: Opdracht
              - href: studiewijzer/hulpmiddelen.qmd
                text: Hulpmiddelen
 
          - section: "Proces"
            contents:
              - href: studiewijzer/organisatie.qmd
                text: Organisatie
              - href: studiewijzer/weekplanning.qmd
                text: Weekplanning               

      - section: "Wolvenpolder"
        contents:
          - href: wolvenpolder/inleiding.qmd
            text: Inleiding
          - href: wolvenpolder/opdracht.qmd
            text: Modelbouw
          - href: wolvenpolder/kalibratie.qmd
            text: Kalibratie

      - section: "Eendragt"
        contents:
          - section: "Tutorial"
            contents:
              - href: wolvenpolder/inleiding.qmd
                text: Inleiding
              - href: wolvenpolder/modelbouw.qmd
                text: Modelbouw
          - section: "Casus"
            contents:
              - href: wolvenpolder/casus.qmd
                text: Opdracht
              - href: wolvenpolder/modelbouw.qmd
                text: Modelbouw


      - href: Rubrics.qmd
        text: Rubrics

      - href: literatuur.qmd
        text: Bronnen

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    include-in-header: header.html
