project:
  type: website
  output-dir: ../docs

website:
  title: "Modelbouw Noorderzijlvest"
  navbar:
    left:
      - text: Wolvenpolder
        href: wolvenpolder/opdracht.qmd
      - text: Eendragt
        href: eendragt/opdracht.qmd
  
  sidebar:
    logo: img/logo.png
    logo-href: https://www.hydroconsult.nl
    style: "docked"
    search: true
    before:
      - text: >
          <div style="text-align: center; padding: 10px 0;">
            <img src="https://lirp.cdn-website.com/ef254e84/dms3rep/multi/opt/2024_SOCIALS_LOGO_SIEBE_BOSCH_HYDROCONSULT-382w.png" 
                 alt="Hydroconsult Logo" 
                 style="max-width: 200px; height: auto;"/>
          </div>
    contents:
      - section: "Wolvenpolder"
        contents:
          - section: "Tutorial"
            contents:
              - href: wolvenpolder/inleiding.qmd
                text: Inleiding
              - href: wolvenpolder/modelbouw.qmd
                text: Modelbouw
          - section: "Casus"
            contents:
              - href: wolvenpolder/casus.qmd
                text: Opdracht
              - href: wolvenpolder/modelbouw.qmd
                text: Modelbouw
          - href: literatuur.qmd
            text: Bronnen

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    include-in-header: header.html
