project:
  type: website
  output-dir: ../docs

website:
  title: "Landelijk water"
  navbar:
    left:
      - text: Wolvenpolder
        href: wolvenpolder/opdracht.qmd
      - text: Eendragt
        href: eendragt/opdracht.qmd
  
  sidebar:
    logo: img/logo_VHL.jpg
    logo-href: https://www.hydroconsult.nl
    style: "docked"
    search: true
    contents:
      - section: "Wolvenpolder"
        contents:
          - section: "Tutorial"
            contents:
              - href: wolvenpolder/inleiding.qmd
                text: Inleiding
              - href: wolvenpolder/modelbouw.qmd
                text: Modelbouw
          - section: "Casus"
            contents:
              - href: wolvenpolder/casus.qmd
                text: Opdracht
              - href: wolvenpolder/modelbouw.qmd
                text: Modelbouw
      - section: "Eendragt"
        contents:
          - section: "Tutorial"
            contents:
              - href: wolvenpolder/inleiding.qmd
                text: Inleiding
              - href: wolvenpolder/modelbouw.qmd
                text: Modelbouw
          - section: "Casus"
            contents:
              - href: wolvenpolder/casus.qmd
                text: Opdracht
              - href: wolvenpolder/modelbouw.qmd
                text: Modelbouw
      - href: literatuur.qmd
        text: Bronnen

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    include-in-header: header.html
