---
title: "Viewers"
---

Deze sectie geeft een overzicht van alle viewers waarmee de uitkomsten van het gekalibreerde model en de gevoeligheidsanalyses kunnen worden beoordeeld.

## Gekalibreerd model

<button id="fullscreen-btn" onclick="toggleFullscreen()">Volledig scherm</button>

<iframe id="interactive-map" src="https://boezemmodel.floodingwebviewer.nl/kalibratieresultaat" width="100%" height="800" frameborder="0" style="border:0;" allowfullscreen></iframe>

<script>
function toggleFullscreen() {
  var iframe = document.getElementById('interactive-map');
  if (iframe.requestFullscreen) {
    iframe.requestFullscreen();
  } else if (iframe.mozRequestFullScreen) { // Firefox
    iframe.mozRequestFullScreen();
  } else if (iframe.webkitRequestFullscreen) { // Chrome, Safari and Opera
    iframe.webkitRequestFullscreen();
  } else if (iframe.msRequestFullscreen) { // IE/Edge
    iframe.msRequestFullscreen();
  }
}
</script>

## Gevoeligheidsanalyse kwel

<button id="fullscreen-btn" onclick="toggleFullscreen()">Volledig scherm</button>

<iframe id="interactive-map" src="https://boezemmodel.floodingwebviewer.nl/gevoeligheidsanalyse/kwel" width="100%" height="800" frameborder="0" style="border:0;" allowfullscreen></iframe>

<script>
function toggleFullscreen() {
  var iframe = document.getElementById('interactive-map');
  if (iframe.requestFullscreen) {
    iframe.requestFullscreen();
  } else if (iframe.mozRequestFullScreen) { // Firefox
    iframe.mozRequestFullScreen();
  } else if (iframe.webkitRequestFullscreen) { // Chrome, Safari and Opera
    iframe.webkitRequestFullscreen();
  } else if (iframe.msRequestFullscreen) { // IE/Edge
    iframe.msRequestFullscreen();
  }
}
</script>


## Gevoeligheidsanalyse representatief maaiveld

<button id="fullscreen-btn" onclick="toggleFullscreen()">Volledig scherm</button>

<iframe id="interactive-map" src="https://boezemmodel.floodingwebviewer.nl/gevoeligheidsanalyse/maaiveld" width="100%" height="800" frameborder="0" style="border:0;" allowfullscreen></iframe>

<script>
function toggleFullscreen() {
  var iframe = document.getElementById('interactive-map');
  if (iframe.requestFullscreen) {
    iframe.requestFullscreen();
  } else if (iframe.mozRequestFullScreen) { // Firefox
    iframe.mozRequestFullScreen();
  } else if (iframe.webkitRequestFullscreen) { // Chrome, Safari and Opera
    iframe.webkitRequestFullscreen();
  } else if (iframe.msRequestFullscreen) { // IE/Edge
    iframe.msRequestFullscreen();
  }
}
</script>


## Gevoeligheidsanalyse drainageweerstand diepe laag

<button id="fullscreen-btn" onclick="toggleFullscreen()">Volledig scherm</button>

<iframe id="interactive-map" src="https://boezemmodel.floodingwebviewer.nl/gevoeligheidsanalyse/diep" width="100%" height="800" frameborder="0" style="border:0;" allowfullscreen></iframe>

<script>
function toggleFullscreen() {
  var iframe = document.getElementById('interactive-map');
  if (iframe.requestFullscreen) {
    iframe.requestFullscreen();
  } else if (iframe.mozRequestFullScreen) { // Firefox
    iframe.mozRequestFullScreen();
  } else if (iframe.webkitRequestFullscreen) { // Chrome, Safari and Opera
    iframe.webkitRequestFullscreen();
  } else if (iframe.msRequestFullscreen) { // IE/Edge
    iframe.msRequestFullscreen();
  }
}
</script>


## Gevoeligheidsanalyse maximaliseren drooglegging

<button id="fullscreen-btn" onclick="toggleFullscreen()">Volledig scherm</button>

<iframe id="interactive-map" src="https://boezemmodel.floodingwebviewer.nl/gevoeligheidsanalyse/drooglegging" width="100%" height="800" frameborder="0" style="border:0;" allowfullscreen></iframe>

<script>
function toggleFullscreen() {
  var iframe = document.getElementById('interactive-map');
  if (iframe.requestFullscreen) {
    iframe.requestFullscreen();
  } else if (iframe.mozRequestFullScreen) { // Firefox
    iframe.mozRequestFullScreen();
  } else if (iframe.webkitRequestFullscreen) { // Chrome, Safari and Opera
    iframe.webkitRequestFullscreen();
  } else if (iframe.msRequestFullscreen) { // IE/Edge
    iframe.msRequestFullscreen();
  }
}
</script>

