## 2 Opdracht

### 2.1 Hulpmiddelen
Het is voor jullie van belang om een breed inzicht te krijgen in de bodem, water en vegetatie in het projectgebied. Daarvoor krijg je lessen over bodemfysica en oppervlaktewaterhydrologie. We werken met verschillende tools en modellen die je inzicht geven in de problematiek, het mogelijk maken om een toetsing uit te voeren van de huidige situatie en om het effect van mogelijke maatregelen te bepalen. Je werkt individueel de opdrachten uit.

Deze syllabus omvat alle instructies die je nodig hebt voor het maken van de opdrachten. Bijbehorende les video's, data en links naar de te gebruiken software en tools staan op Moodle. 
Meer informatie over de planning, organisatie en inhoud van de lessen is te vinden onder het kopje 'Proces'. 


<mark> xxx nog aanpassen!! </mark>
Op internet is zeer veel informatie te vinden over de Eendragt polder en de plannen die daar de afgelopen jaren zijn bedacht en uitgevoerd. Gebruik deze informatie voor de analyse van de mogelijke maatregelen en de reeds uitgevoerde maatregelen en de bepaling van de effecten ervan.

Enkele bruikbare links/documenten (niet volledig, we verwachten dat jullie zelf een literatuurstudie doen van div. bronnen op internet): 

<mark> xxx nog toevoegen!! </mark>