## 2 Opdracht

In dit hoofdstuk worden de opdracht nader geïntroduceerd. Aangegeven is welke hulpmiddelen je daarbij kunt gebruiken. 

### 2.1 Opdrachtomschrijving

#### 2.1.1	NBW Toetsing en analyse oude situatie

Deze casus is opgezet rond de Eendragt polder. Je maakt kennis met het analyseren van extreme waarden in het waterbeheer. Zulke analyses voeren we uit om bijvoorbeeld de kans op een inundatie (overstroming) te kunnen bepalen. In het Nationaal Bestuursakkoord Water (NBW) is afgesproken dat alle watersystemen van waterschappen eens in de 5 jaar getoetst worden.
Het NBW bevat afspraken rondom veiligheid en wateroverlast (te veel) en procesafspraken rond watertekorten, verdroging, verzilting (te weinig), water(bodem)kwaliteit, sanering waterbodems (te vies) en ecologie (ecologisch te arm water).

<mark>xxx moeten we hier nog iets zeggen over dat NBW inmiddels is vervangen door ander beleid maar nog wel gebruikt? Hoe verwoorden we dit? </mark> 

Specifiek voor wateroverlast die optreedt wanneer regionale watergangen buiten hun oevers treden zijn landelijke uniforme werknormen opgesteld, zie tabel 1.

| Normklasse gerelateerd aan grondgebruiktype | Maaiveldcriterium [%] | Basis werkcriterium [1/j] |
|----------|----------|----------|
| Grasland | 5 procent | 1/10 |
| Akkerbouw | 1 procent | 1/25 |
| Hoogwaardige land- en tuinbouw | 1 procent | 1/50 |
| Glastuinbouw | 1 procent | 1/50 |
| Bebouwd gebied | 0 procent | 1/100 |
::: {.caption}
Tabel 1: Inundatienormen uit het NBW.
:::

In deze casus zul je de twee meest gebruikte methodes leren toepassen: de tijdreeksmethode en de stochastenmethode. Beide methodes stellen je in staat om waterstanden en afvoeren te berekenen die een bepaalde kans op overschrijding hebben. Je leert statistiek en kansrekening toe te passen op neerslagvolumes, afvoeren en waterstanden en je vergroot je modelleervaardigheden.

Onderdeel van de opdracht is om met behulp van D-HYDRO een analyse te maken van de hydrologische toestand van het oppervlaktewater voorafgaand aan de peilaanpassingen en functiewijzigingen van de Eendragt polder, inclusief een overzicht van locaties met wateroverlast (waar wordt niet voldaan aan de NBW normen). Welke wateropgave bereken je? Wat zijn de eisen en wensen voor het plangebied op basis van deze berekende wateropgave?

Om de NBW toetsing snel en efficiënt uit te voeren ga je gebruik maken van verschillende tools. Een nadere toelichting op het uitvoeren van een NBW toetsing is te vinden in deze syllabus onder het kopje <mark> xxx </mark>. 

Naast de NBW toetsing bepaal je met de online applicatie van de waterwijzer Landbouw in hoeverre er een optimale match is tussen het landgebruik, de bodem en het waterregime van de Eendragt polder. Aan jullie hierbij de vraag om te analyseren hoe veel te nat / te droog het was in het gebied. In welke gebieden was het te nat? Wat is de zogenaamde natschade (zuurstofstress) en welke opbrengstderving wordt hierdoor veroorzaakt? Tevens kunnen er ook gebieden zijn waar de drooglegging goed is, mogelijk zelfs te groot. Wat is de droogtestress voor deze gebieden? De berekening van de droogtestress geeft je inzicht in droogteschade en kan dienen als opmaat naar mogelijke aanvullende maatregelen. 

Het gebruik van de online applicatie van de Waterwijzer Landbouw wordt in een van de werkcolleges verder toegelicht. 

#### 1.1.3	Analyse plannen en mogelijke oplossingen

<mark> xxx check of alles nog klopt!!  </mark>. 

De analyse van de oude situatie (wateroverlast/wateropgave en doelrealisatie landbouw) heb je afgerond. Nu is het tijd om mogelijke oplossingen te formuleren (eigen ideeën op basis van de analyses). Ook ga je de reeds uitgevoerde oplossingen in het gebied analyseren op effectiviteit en (klimaat)robuustheid. Wat vindt je  van de uitgevoerde oplossingen en voorgestelde plannen? Zijn de genomen maatregelen afdoende om het gebied de komende jaren effectief te kunnen gebruiken als landbouwgebied? Sluiten de huidige omstandigheden aan bij de beoogde natuurdoelen? Wat zijn eventuele knelpunten voor de landbouw en als je deze locaties omvormt tot natuur, welke natuurdoelen zijn dan haalbaar? Of omgekeerd; zijn er gebieden met een natuurfunctie die toch beter landbouwfunctie hebben?
