## 1 Introductie


### 1.3 Toetsing
Je sluit deze casus af met twee toetsen:

::: {.columns}
::: {.column width="50%"}
#### Landelijk water modelleren  
#### (individueel)

::: {.columns}
::: {.column width="50%"}
Weging  
Minimum cijfer  
Toetsvorm  
Resultaatschaal  
:::
::: {.column width="50%"}
3   
5,5  
Opdracht  
Toetsen 1-10. 1 decimaal 5,5 geslaagd   
:::
:::




:::
::: {.column width="50%"}
#### Advies landelijk water  
#### (in groepen van 3 of 4 studenten)
::: {.columns}
::: {.column width="50%"}
Weging  
Minimum cijfer  
Toetsvorm  
Resultaatschaal  
:::
::: {.column width="50%"}
4   
5,5  
Opdracht  
Toetsen 1-10. 1 decimaal 5,5 geslaagd  
(alleen voor voltijd)  
:::
:::

:::
:::

#### 1.3.1 Landelijk water modelleren

De volgende leerdoelen staan centraal in de toets Landelijk water modelleren:

1.	Good Modellering Practices hanteren bij hydrologisch modelleren
2.	Een oppervlaktewatersysteem modelleren
3.	Een oppervlaktewatersysteem toetsen
4.	Effecten van waterhuishoudkundige ingrepen op landbouw en natuur bepalen

Voor de casus Landelijk water ga je met verschillende modellen aan de slag, om kennis over modellering op te doen zodat je daarmee een advies kunt geven aan het waterschap over de Eendragt polder. Deze toets bestaat uit de individuele beoordeling van de (oefen)modellen die je gaat maken en gebruiken om uiteindelijk de analyse en toetsing van de Eendragt polder te kunnen uitvoeren.
 
Om de gemaakte of gebruikte modellen goed te kunnen beoordelen vragen we om per deelopdracht/deelmodel een logboek te maken, waarin je aangeeft welke stappen je doorlopen hebt en welke resultaten dit opgeleverd heeft. Voor deze toets ga je werken met D-Hydro inclusief bijbehorende (Excel)tools, GIS en de webapplicatie van de waterwijzer Landbouw. 

De volgende deelopdrachten/deelmodellen moeten worden gemaakt en uitgewerkt worden in een logboek:

<mark> xxx hier nog uitleg geven over 'vraag boxen', 'info boxen' etc. </mark>

<mark> xxx nog updaten!!</mark> 

<mark> **Deel 1 (Woensdag 22 mei, 17.00 uur op Moodle)**  </mark>

<mark> 1.	Sobek 0D Rainfall Runoff (RR) model van de Wolvenpolder  
2.	Sobek 1DFlow model van de Leijgraaf  
3.	Sobek 0D (RR) -1D model van de Leijgraaf  
4.	Toetsing natschade/droogteschade a.d.h.v. Waterwijzers Landbouw en Natuur uitgevoerd voor het stroomgebied van de Geleenbeek  </mark>

<mark> **Deel 2 (Maandag 10 juni, 17.00 uur op Moodle)**  </mark>

<mark> 5.	NBW toetsing uitgevoerd a.d.h.v. Stochastentool, Sobek en NBW toetsingstool voor de Zeven Blokkenpolder </mark>

Het logboek van deze opdrachten lever je in op Moodle (in twee delen). Op welke criteria dit logboek beoordeeld wordt kan je vinden in de rubric (zie menu aan de linke kant).

Het logboek wordt individueel beoordeeld met een cijfer.

#### 1.3.2 Advies landelijk water

De volgende leerdoelen staan centraal in de toets Advies landelijk water:

5.	Relevante karakteristieken van het bodem- en watersysteem waarderen
6.	Eisen en wensen voor een plangebied vaststellen
7.	Haalbaarheid van oplossingen beoordelen

Voor de toets Advies landelijk water maken jullie met je groep een video-opname (screencast inclusief webcam) van een presentatie in PowerPoint van maximaal 15 minuten (let op: dit is echt een harde eis, video’s die langer zijn dan 15 minuten worden met een onvoldoende beoordeeld), waarin jullie samen een toelichting geven op:

-	de opbouw van het gebied (oude en nieuwe situatie),
-	de toetsing van de oude situatie (inundatie en doelrealisatie landbouw en natuur),
-	de eisen en wensen voor het plangebied (o.a. op basis van de toetsing),
-	de mogelijke oplossingen (zelf bedachte maatregelen op basis van de toetsing) en 
-	de analyse van de reeds uitgevoerde oplossingen op effectiviteit en (klimaat)robuustheid. 

Het product wordt beoordeeld met een cijfer. De leidraad voor de beoordeling is opgenomen in de rubric (zie menu aan de linke kant).
<mark> Deadline voor Advies landelijk water is vrijdag 14 juni, 17.00 uur.</mark>

